<?php if($management): ?>
<form method="post" id="rack-editor" class="site-editor" <?= $rackEditing?'':'hidden' ?>>
<?php icct_nms_token(); ?><input type="hidden" name="action" value="save_rack_profile"><input type="hidden" name="rack_profile_id" value="<?= icct_nms_h(is_string($rackValues['rack_profile_id'] ?? '') ? ($rackValues['rack_profile_id'] ?? '') : '') ?>">
<div class="type-editor-heading"><h2 id="rack-editor-title"><?= empty($rackValues['rack_profile_id'])?'Add':'Edit' ?> Rack Configuration</h2><div><button type="button" id="cancel-rack-config" class="button">Cancel</button><button type="submit" class="button primary">Save</button></div></div>
<div class="site-fields">
<label class="field"><span class="field-label">Rack Name *</span><input name="rack_name" required maxlength="150" placeholder="Enter rack name" value="<?= icct_nms_h(is_string($rackValues['rack_name'] ?? '') ? ($rackValues['rack_name'] ?? '') : '') ?>"></label>
<?php foreach(['rack_count'=>'Number of Racks','unit_count'=>'Units per Rack'] as $key=>$label): ?><label class="field"><span class="field-label"><?= $label ?> *</span><input type="number" name="<?= $key ?>" min="1" max="100" step="1" required placeholder="Enter 1–100" value="<?= icct_nms_h(is_scalar($rackValues[$key] ?? '') ? ($rackValues[$key] ?? '') : '') ?>"></label><?php endforeach; ?>
</div><p>Select this configuration on a node to create its racks. Each rack receives the specified unit capacity. Existing device placements are protected when applying changes.</p>
</form><?php endif; ?>
<section aria-label="Rack configurations"><label class="field site-search"><span class="field-label">Search racks</span><input type="search" id="rack-profile-search" placeholder="Search by rack name"></label>
<div class="site-table-wrap"><table class="site-table"><thead><tr><th>Rack Name</th><th>Number of Racks</th><th>Units per Rack</th><th>Actions</th></tr></thead><tbody>
<?php foreach($rackProfiles as $key=>$profile): ?><tr data-rack-profile-search="<?= icct_nms_h(mb_strtolower($profile['name'])) ?>"><td><?= icct_nms_h($profile['name']) ?></td><td><?= (int)$profile['rack_count'] ?></td><td><?= (int)$profile['unit_count'] ?> U</td><td><?php if($management): ?><button type="button" class="icon-button" aria-label="Edit <?= icct_nms_h($profile['name']) ?>" data-edit-rack-profile="<?= icct_nms_h(json_encode(['rack_profile_id'=>$key,'rack_name'=>$profile['name'],'rack_count'=>$profile['rack_count'],'unit_count'=>$profile['unit_count']],JSON_THROW_ON_ERROR)) ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16 12-12 4 4-12 12-5 1zM14 6l4 4"/></svg></button><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php if(!$rackProfiles): ?><p class="empty-state">No rack configurations yet. Add a configuration, then select it on a node.</p><?php endif; ?></section>
