<section class="topology-configuration">
<div class="titlebar"><h1>Topology Configuration</h1><a class="button" href="topology.php">View Topology</a></div>
<nav class="presets-tabs" aria-label="Topology configuration sections">
<?php foreach(['connections'=>'Device Connections','networks'=>'Networks','discovered'=>'Discovered Devices'] as $key=>$label): ?><a href="?tab=<?= $key ?>" <?= $tab===$key?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach; ?>
</nav>
<?php if($tab==='connections'): ?>
<h2>Manual device connections</h2>
<?php if($management): ?><form method="post" class="topology-config-form">
<?php icct_nms_token(); ?><input type="hidden" name="action" value="save_link"><input type="hidden" name="link_id" value="<?= icct_nms_h($edit['link_id']??($_GET['edit']??'')) ?>">
<div class="form-grid">
<?php foreach(['source'=>'Source Device','target'=>'Target Device'] as $key=>$label): ?><div class="field"><label for="<?= $key ?>"><?= $label ?> * <span class="connection-help" tabindex="0" role="img" aria-label="<?= $key==='source'?'Choose the device where the connection starts. Search by device name or address.':'Choose the connected device. It must be different from the source device. Search by name or address.' ?>" data-tooltip="<?= $key==='source'?'Choose the device where the connection starts. Search by device name or address.':'Choose the connected device. It must be different from the source device. Search by name or address.' ?>">ⓘ</span></label><select class="connection-device-select" id="<?= $key ?>" name="<?= $key ?>" required><option value="">Select device</option><?php foreach($devices as $d): ?><option value="<?= (int)$d['id'] ?>" data-address="<?= icct_nms_h($d['hostname']??'') ?>" <?= (int)($edit[$key]??0)===(int)$d['id']?'selected':'' ?>><?= icct_nms_h($d['description']) ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
<div class="field"><label for="profile">Network Connection *</label><select id="profile" name="profile" required><option value="">Select connection type</option><?php foreach($profiles as $key=>$p): ?><option value="<?= icct_nms_h($key) ?>" <?= ($edit['profile']??'')===$key?'selected':'' ?>><?= icct_nms_h($p['name']) ?></option><?php endforeach; ?></select></div>
<?php foreach(['source_port'=>'Source Port','target_port'=>'Target Port'] as $key=>$label): ?><div class="field"><label for="<?= $key ?>"><?= $label ?></label><input id="<?= $key ?>" name="<?= $key ?>" maxlength="100" value="<?= icct_nms_h($edit[$key]??'') ?>" placeholder="Interface name or port number"></div><?php endforeach; ?>
</div><div class="type-editor-actions"><a class="button" href="?tab=connections">Cancel</a><button class="button primary">Save Connection</button></div></form><?php endif; ?>
<h2>Automatic device discovery</h2>
<?php if($management): ?><form method="post" class="topology-config-form">
<?php icct_nms_token(); ?>
<div class="form-grid"><div class="field"><label for="discoveryDevice">Device * <span class="connection-help" tabindex="0" role="img" aria-label="Select the device that reports neighbours using its saved SNMP credentials. Save collection settings before requesting discovery." data-tooltip="Select the device that reports neighbours using its saved SNMP credentials. Save collection settings before requesting discovery.">ⓘ</span></label><select class="connection-device-select" id="discoveryDevice" name="host_id" required><option value="">Select device</option><?php foreach($devices as $d): ?><option value="<?= (int)$d['id'] ?>" data-address="<?= icct_nms_h($d['hostname']??'') ?>"><?= icct_nms_h($d['description']) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="interval_seconds">Collection Interval (seconds)</label><input id="interval_seconds" type="number" name="interval_seconds" min="300" max="86400" value="300" required></div><div class="field"><label for="stale_seconds">Stale After (seconds)</label><input id="stale_seconds" type="number" name="stale_seconds" min="600" max="604800" value="900" required></div><div class="field"><label for="refresh_seconds">Display Refresh (seconds)</label><input id="refresh_seconds" type="number" name="refresh_seconds" min="10" max="300" value="30" required></div></div>
<fieldset class="discovery-methods"><legend>Collection methods</legend><?php foreach(icct_backend_nd_method_labels() as $key=>$label): ?><label><input type="checkbox" name="methods[]" value="<?= $key ?>"> <?= icct_nms_h($label) ?></label><?php endforeach; ?><label><input type="checkbox" name="collection_enabled" value="1"> Enable collection</label></fieldset><p>Uses this device’s saved SNMP credentials. Enable LLDP/CDP in Protocol Config to collect those neighbours. ARP and MAC tables are observations, not confirmed direct links.</p><button class="button primary" name="action" value="save_discovery">Save Discovery Settings</button> <button class="button" id="selectedDiscoverNow" name="action" value="discover_now" disabled>Discover Now</button></form><?php endif; ?>
<?php $discoverySettings=[]; foreach($devices as $d): $assignment=icct_nms_discovery_assignment($d['id']);$discoverySettings[$d['id']]=['methods'=>icct_backend_nd_protocols(($assignment['methods']??'')?:($assignment['protocol']??'')),'collection_enabled'=>(bool)($assignment['collection_enabled']??false),'interval_seconds'=>$assignment['interval_seconds']??300,'stale_seconds'=>$assignment['stale_seconds']??900,'refresh_seconds'=>$assignment['refresh_seconds']??30]; endforeach; ?>
<h2>Manual connections and automatically detected devices</h2>
<div class="topology-discovery-filters"><div class="field"><label for="connectionSearch">Search connections</label><input type="search" id="connectionSearch" placeholder="Device, address, port or method"></div><div class="field"><label for="connectionOrigin">Connection source</label><select id="connectionOrigin"><option value="">All connections</option><option>Manual</option><option>Automatic</option></select></div></div>
<div class="topology-table-scroll"><table class="site-table" id="connectionResults"><thead><tr><th>Source / Port</th><th>Target / Port</th><th>Connection / Method</th><th>Source</th><th>Status</th><th>Last Detected</th><th>Actions</th></tr></thead><tbody>
<?php foreach($links as $key=>$link): ?><tr data-origin="Manual"><td><?= icct_nms_h($byId[$link['source']]['description'].' / '.($link['source_port']?:'Not specified')) ?></td><td><?= icct_nms_h($byId[$link['target']]['description'].' / '.($link['target_port']?:'Not specified')) ?></td><td><?= icct_nms_h($profiles[$link['profile']]['name']??'Custom') ?></td><td>Manual</td><td><span class="device-status other">Configured</span></td><td>—</td><td><?php if($management): ?><a class="button" href="?tab=connections&amp;edit=<?= icct_nms_h($key) ?>">Edit</a><form method="post" class="topology-inline-form"><?php icct_nms_token(); ?><input type="hidden" name="action" value="delete_link"><input type="hidden" name="link_id" value="<?= icct_nms_h($key) ?>"><button class="button" aria-label="Remove connection">Remove</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php foreach($observations as $d): ?><tr data-origin="Automatic"><td><?= icct_nms_h($d['reporter'].' / '.($d['port']?:'Not specified')) ?></td><td><?= icct_nms_h($d['name'].' / '.($d['remote_port']?:'Not specified')) ?><?php if($d['address']): ?><div><?= icct_nms_h($d['address']) ?></div><?php endif; ?></td><td><?= icct_nms_h($d['protocol']) ?><div><?= icct_nms_h($d['detail']) ?></div></td><td>Automatic</td><td><span class="device-status <?= $d['status']==='Current'?'online':'other' ?>"><?= icct_nms_h($d['status']) ?></span></td><td><?= icct_nms_h($d['last_check']) ?></td><td>—</td></tr><?php endforeach; ?>
<tr id="connectionEmpty" <?= $links||$observations?'hidden':'' ?>><td colspan="7">No matching manual connections or detected devices.</td></tr></tbody></table></div>
<nav class="inventory-pagination" aria-label="Connection results pages"><label>Items per page: <select id="connectionSize"><option>10</option><option selected>25</option><option>50</option></select></label><span id="connectionRange" aria-live="polite"></span><div class="page-controls"><label><span class="sr-only">Page</span><select id="connectionPageNumber"></select></label><span id="connectionPageCount"></span><button type="button" id="connectionPrevious" aria-label="Previous page">‹</button><button type="button" id="connectionNext" aria-label="Next page">›</button></div></nav>
<script id="topologyDiscoverySettings" type="application/json"><?= json_encode($discoverySettings,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<?php elseif($tab==='networks'): ?>
<?php if(!$automation): ?><p>Your account does not have Cacti Automation permission.</p><?php else: ?>
<?php if($networkEdit!==null): require __DIR__.'/network_configuration.php'; else: ?>
<div class="titlebar"><h2>Discovery networks</h2><a class="button primary" href="?tab=networks&amp;network_edit=0">Add Network</a></div>
<table class="site-table"><thead><tr><th>Network</th><th>Subnet Range</th><th>Enabled</th><th>Addresses / Up / SNMP</th><th>Last Started</th><th>Result</th><th>Actions</th></tr></thead><tbody><?php foreach($networks as $network): ?><tr><td><?= icct_nms_h($network['name']) ?></td><td><?= icct_nms_h($network['subnet_range']) ?></td><td><?= $network['enabled']==='on'?'Enabled':'Disabled' ?></td><td><?= (int)$network['total_ips'] ?> / <?= (int)$network['up_hosts'] ?> / <?= (int)$network['snmp_hosts'] ?></td><td><?= icct_nms_h($network['last_started']) ?></td><td><?= icct_nms_h($network['last_status']) ?></td><td><a class="button" href="?tab=networks&amp;network_edit=<?= (int)$network['id'] ?>">Configure</a><a class="button" href="?tab=discovered&amp;network=<?= (int)$network['id'] ?>">Discovered Devices</a><form method="post" class="topology-inline-form"><?php icct_nms_token(); ?><input type="hidden" name="action" value="run_network"><input type="hidden" name="network_id" value="<?= (int)$network['id'] ?>"><button class="button" <?= $network['enabled']!=='on'?'disabled':'' ?>>Discover Now</button></form></td></tr><?php endforeach; ?><?php if(!$networks): ?><tr><td colspan="7">No discovery networks configured.</td></tr><?php endif; ?></tbody></table><?php endif; endif; ?>
<?php else: ?>
<div class="titlebar"><h2>Discovered devices and neighbours</h2><?php if($automation): ?><a class="button" href="<?= icct_nms_h($config['url_path']) ?>automation_devices.php">Manage / Add to Cacti</a><?php endif; ?><a class="button" href="?tab=discovered">Refresh</a></div>
<div class="topology-discovery-filters"><div class="field"><label for="discoveredSearch">Search</label><input type="search" id="discoveredSearch" placeholder="Device, address, reporter or port"></div><div class="field"><label for="discoveredProtocol">Method</label><select id="discoveredProtocol"><option value="">All methods</option><?php foreach(['Cacti Network','LLDP','CDP','ARP','FDB'] as $method): ?><option><?= $method ?></option><?php endforeach; ?></select></div><div class="field"><label for="discoveredNetwork">Network</label><select id="discoveredNetwork"><option value="">All networks</option><?php foreach($networks as $network): ?><option value="<?= (int)$network['id'] ?>" <?= (string)($_GET['network']??'')===(string)$network['id']?'selected':'' ?>><?= icct_nms_h($network['name']) ?></option><?php endforeach; ?></select></div></div>
<p id="discoveredCount" aria-live="polite"></p><div class="topology-table-scroll"><table class="site-table" id="discoveredTable"><thead><tr><th>Device / Identity</th><th>Address</th><th>Network / Reporting Device</th><th>Method</th><th>Local / Remote Port</th><th>Status</th><th>Last Check</th><th>Evidence</th></tr></thead><tbody>
<?php foreach($coreDevices as $d): $status=$d['up']?'Up':'Down'; ?><tr data-method="Cacti Network" data-network="<?= (int)$d['network_id'] ?>"><td><?= icct_nms_h($d['sysName']?:($d['hostname']?:'Not detected')) ?></td><td><?= icct_nms_h($d['ip']) ?></td><td><?= icct_nms_h($d['network']) ?></td><td>Cacti Network</td><td>—</td><td><span class="device-status <?= icct_nms_status_class($status) ?>"><?= $status ?></span></td><td><?= icct_nms_h($d['last_check']) ?></td><td><?= $d['known']?'Known to Cacti':'Not added' ?> · SNMP <?= $d['snmp']?'Up':'Down' ?></td></tr><?php endforeach; ?>
<?php foreach($observations as $d): ?><tr data-method="<?= icct_nms_h($d['protocol']) ?>" data-network=""><td><?= icct_nms_h($d['name']) ?></td><td><?= icct_nms_h($d['address']) ?></td><td><?= icct_nms_h($d['reporter']) ?></td><td><?= icct_nms_h($d['protocol']) ?></td><td><?= icct_nms_h($d['port'].' / '.$d['remote_port']) ?></td><td><span class="device-status <?= $d['status']==='Current'?'online':'other' ?>"><?= $d['status'] ?></span></td><td><?= icct_nms_h($d['last_check']) ?></td><td><?= icct_nms_h($d['detail']) ?></td></tr><?php endforeach; ?><tr id="discoveredEmpty" hidden><td colspan="8">No matching discovery results.</td></tr></tbody></table></div><nav class="inventory-pagination discovery-pagination" aria-label="Discovery results pages"><label>Items per page: <select id="discoveredSize"><option>10</option><option selected>25</option><option>50</option></select></label><span id="discoveredRange" aria-live="polite"></span><div class="page-controls"><label><span class="sr-only">Page</span><select id="discoveredPageNumber"></select></label><span id="discoveredPage"></span><button type="button" id="discoveredPrevious" aria-label="Previous page">‹</button><button type="button" id="discoveredNext" aria-label="Next page">›</button></div></nav>
<p>Current LLDP/CDP neighbours that uniquely match an accessible Cacti device appear as dashboard connections. ARP/FDB entries remain observations. Add unknown devices to Cacti before including them in the device topology.</p>
<?php endif; ?></section>
