<?php if(is_realm_allowed(3)) { ?>
<?php if($workspace_section==='identity' && $workspace_host && $workspace_management_proposals) { ?>
<section class="nms-panel"><h2 data-nms-tip="Alternative addresses do not prove that the management IP changed. Verify from the assigned collector, then review before applying. Verification uses this device's SNMP credentials, a timeout of up to 2 seconds and at most 2 retries. Normal polling settings are unchanged.">Alternative addresses</h2>
<?php foreach($workspace_management_proposals as $proposal) { ?><article class="nms-workspace-finding"><h3><?php print nms_h($proposal['old_address'].' → '.$proposal['target']); ?></h3><p><?php print nms_h($proposal['reason']); ?></p><p><?php print nms_h($proposal['source'].' · ifIndex '.$proposal['ifindex'].' · '.$proposal['observed_at']); ?></p>
<?php if($proposal['eligible'] && $proposal['chassis']) { ?><form method="post" action="<?php print nms_h(nms_workspace_url('identity',$workspace_id)); ?>"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="workspace_action" value="verify_management_ip"><input type="hidden" name="proposal_id" value="<?php print nms_h($proposal['id']); ?>"><button type="submit">Verify proposed address</button></form><?php } elseif(!$proposal['chassis']) { ?><p>Chassis serial/model evidence is unavailable. A verified identity match is required before this workflow can change the address.</p><?php } ?></article><?php } if(!$workspace_management_proposals) { ?><p>No current eligible alternative-address evidence. Collect fresh device-owned addresses first.</p><?php } ?></section>
<?php } if($workspace_management_review) { $review=$workspace_management_review;$job=$review['job']; ?>
<section class="nms-panel"><h2>Review management-IP change</h2>
<p><strong><?php print nms_h($job['old_address'].' → '.$job['target']); ?></strong></p>
<p>Device ID <?php print (int)$job['host_id']; ?> · Collector <?php print (int)$job['poller_id']; ?> · Verified <?php print nms_h($job['verified_at']); ?></p>
<p>The new address returned matching chassis and device-owned address evidence. Applying updates the existing Cacti device and checks its graph/data-source associations. This changes the destination used for polling; it does not combine device records.</p>
<p><?php print nms_h($review['admission']['message']); ?></p>
<?php foreach($review['admission']['matches'] as $match) { ?><p><a href="<?php print nms_h(nms_workspace_url('identity',$match['host_id'])); ?>">Review conflicting record</a> <?php print nms_h($match['reason']); ?></p><?php } ?>
<?php if(!$review['admission']['blocked'] && $job['status']==='verified') { ?><form method="post" action="<?php print nms_h(nms_workspace_url('identity',$job['host_id'])); ?>"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="workspace_action" value="apply_management_ip"><input type="hidden" name="change_id" value="<?php print (int)$job['id']; ?>"><input type="hidden" name="revision" value="<?php print nms_h($review['revision']); ?>"><button type="submit">Confirm management-IP change</button></form><?php } ?></section>
<?php } ?>
<?php if($workspace_management) { ?><section class="nms-panel"><h2 data-nms-tip="Latest 50 requests made by your account for devices you can currently access.">Address change history</h2>
<div class="nms-table-wrap"><table class="nms-table"><thead><tr><th>Device / old → proposed</th><th>Status</th><th>Requested / verified</th><th>Actions</th></tr></thead><tbody>
<?php foreach($workspace_management as $job) { ?><tr><td><?php print nms_h($job['description']); ?><p><?php print nms_h($job['old_address'].' → '.$job['target']); ?></p></td><td><?php print nms_h($job['status']); ?><p><?php print nms_h($job['error']); ?></p></td><td><?php print nms_h($job['requested_at'].' / '.($job['verified_at']?:'Not verified')); ?></td><td>
<?php if($job['status']==='verified') { ?><a href="<?php print nms_h(nms_workspace_url('identity',$job['host_id'],['management_review'=>$job['id']])); ?>">Review address change</a><?php } ?>
<?php if(in_array($job['status'],['queued_verify','verified','queued_apply'],true)) { ?><form method="post" action="<?php print nms_h(nms_workspace_url($workspace_section,$workspace_id)); ?>"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="workspace_action" value="cancel_management_ip"><input type="hidden" name="change_id" value="<?php print (int)$job['id']; ?>"><button type="submit">Cancel address request</button></form><?php } ?>
<details><summary>Recorded verification</summary><pre><?php print nms_h($job['result_json']); ?></pre></details></td></tr><?php } if(!$workspace_management) { ?><tr><td colspan="4">No management-IP requests in this selection.</td></tr><?php } ?>
</tbody></table></div></section><?php } ?><?php } ?>
