<?php /** Advertised neighbours are observations, not verified reachable inventory. */ ?>
<section class="nms-panel"><h2>Neighbour observations</h2><p>Verification uses the device’s configured SNMP credentials and timeout (up to 2 seconds), with at most 2 retries. Normal Cacti polling settings are unchanged.</p><p>LLDP/CDP advertisements do not prove that a management address is reachable.</p><div class="nms-table-wrap"><table class="nms-table"><thead><tr><th>Reporting device</th><th>Local port</th><th>Advertised neighbour / remote port</th><th>Advertised management addresses</th><th>Protocol / collection</th><th>Evidence</th></tr></thead><tbody>
<?php $count=0;foreach($workspace_discovery['snapshots'] as $snapshot) {
if(!in_array($snapshot['protocol'],['lldp','cdp'],true) || ($workspace_id && (int)$snapshot['host_id']!==$workspace_id))continue;
$reporter=$workspace_discovery['hosts'][$snapshot['host_id']] ?? null;if(!$reporter)continue;
foreach($snapshot['data']['neighbors'] ?? [] as $neighbor) { $count++;
?><tr><td><?php print nms_h($reporter['description']); ?></td><td><?php print nms_h($neighbor['local_port'] ?? $neighbor['local_ifindex'] ?? 'Not reported'); ?></td><td><?php print nms_h(($neighbor['remote_name'] ?? $neighbor['peer_key'] ?? 'Not reported').' / '.($neighbor['remote_port'] ?? 'Not reported')); ?></td><td><?php if(empty($neighbor['management_addresses'])) { print 'Not reported or not collected'; } else { foreach($neighbor['management_addresses'] as $address) { ?><p><?php print nms_h($address['address'].' · '.$address['source']); ?><br><?php print nms_h(!empty($address['requires_scope'])?'Needs interface scope; not ready for verification':'Advertised only; reachability not verified'); ?></p><?php }} foreach($neighbor['management_address_errors']??[] as $error) { ?><p><?php print nms_h($error); ?></p><?php } ?></td><td><?php print nms_h(strtoupper($snapshot['protocol']).' · '.($snapshot['succeeded_at'] ?: 'No successful collection')); ?></td><td><?php print nms_h(empty($snapshot['valid'])?'Configuration changed':$snapshot['status']); ?><details><summary>Advertised evidence</summary><pre><?php print nms_h(json_encode($neighbor,JSON_PRETTY_PRINT|JSON_INVALID_UTF8_SUBSTITUTE)); ?></pre></details></td></tr>
<?php }}if(!$count) { ?><tr><td colspan="6">No neighbour observations in this selection.</td></tr><?php } ?></tbody></table></div></section>
<section class="nms-panel"><h2>Neighbour onboarding candidates</h2>
<p>These candidates come from advertised addresses. A matching address is a reason to review an existing record, not proof of one physical device. Verification runs ICMP and SNMP from the reporting device’s collector, using that device’s existing SNMP credentials and context. Verify only if those credentials are appropriate for the advertised neighbour. Verification does not add a device; use a completed verification below to review device addition.</p>
<div class="nms-table-wrap"><table class="nms-table"><thead><tr><th>Candidate / address</th><th>Reporting device / ports</th><th>Evidence</th><th>Existing visible records</th></tr></thead><tbody>
<?php foreach($workspace_candidates as $candidate) { ?><tr>
<td><?php print nms_h($candidate['name']?:$candidate['identity']); ?><p><?php print nms_h($candidate['advertised_address']); ?></p><strong><?php print nms_h($candidate['state']); ?></strong>
<?php if($candidate['eligible'] && is_realm_allowed(3)) { ?><form method="post" action="<?php print nms_h(nms_workspace_url('neighbours',$workspace_id)); ?>">
<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="workspace_action" value="verify_candidate"><input type="hidden" name="reporter_id" value="<?php print (int)$candidate['reporter_id']; ?>"><input type="hidden" name="candidate_id" value="<?php print nms_h($candidate['id']); ?>"><button type="submit">Verify with reporter SNMP settings</button></form><?php } ?></td>
<td><?php print nms_h($workspace_discovery['hosts'][$candidate['reporter_id']]['description']); ?><p><?php print nms_h($candidate['local_port'].' → '.$candidate['remote_port']); ?></p></td>
<td><?php print nms_h(strtoupper($candidate['protocol']).' · '.$candidate['observed_at']); ?><p><?php print nms_h($candidate['confidence']); ?></p></td>
<td><?php foreach($candidate['matches'] as $match) { $peer=$workspace_discovery['hosts'][$match['host_id']]??null;foreach($devices as $visible_device)if((int)$visible_device['id']===$match['host_id']){$peer=$visible_device;break;} ?><p><a href="<?php print nms_h(nms_workspace_url('identity',$match['host_id'])); ?>"><?php print nms_h($peer['description']); ?></a> · <?php print nms_h($match['reason']); ?></p><?php } if(!$candidate['matches'])print 'No matching address among visible devices in this site and collector. This does not establish uniqueness.'; ?></td>
</tr><?php } if(!$workspace_candidates) { ?><tr><td colspan="4">No advertised management-address candidates in this selection. Collect current LLDP/CDP evidence to populate this list.</td></tr><?php } ?>
</tbody></table></div></section>

<?php require __DIR__.'/verification_history.php'; ?>

<?php require __DIR__.'/onboarding.php'; ?>
