<?php /** Scan history and bounded results are visible only with current Automation authorization. */ ?>
<?php if($workspace_scan_history) { ?><section class="nms-panel"><h2>Scan runs</h2><p>Native Cacti scans can add devices according to their saved rules. Supplemental probes only report responses. A completed scan does not mean every target responded.</p>
<div class="nms-table-wrap nms-workspace-fit-table"><table class="nms-table" data-server-pagination="true"><thead><tr><th>Run / network</th><th>Kind / collector</th><th>Status / progress</th><th>Requested / finished</th><th>Result / action</th></tr></thead><tbody>
<?php foreach($workspace_scan_history['rows'] as $scan) { ?><tr><td>#<?php print (int)$scan['id']; ?> · <?php print nms_h($scan['name'] ?: 'Removed network #'.$scan['network_id']); ?></td><td><?php print nms_h($scan['kind']); ?> · <?php print (int)$scan['poller_id']; ?></td><td><?php print nms_h($scan['status'].($scan['cancel_requested']?' (cancellation requested)':'')); ?><br><?php print (int)$scan['progress_cursor'].' / '.(int)$scan['task_count']; ?><small><?php print nms_h($scan['error']); ?></small></td><td><?php print nms_h($scan['requested_at'].' / '.($scan['finished_at'] ?: 'Not finished')); ?></td><td><a href="<?php print nms_h(nms_workspace_url($workspace_section,$workspace_id,['run_id'=>$scan['id'],'scan_page'=>$workspace_scan_history['page']])); ?>#scan-result">View results</a>
<?php if(in_array($scan['status'],['queued','dispatching','running'],true) && !$scan['cancel_requested']) { ?><form method="post" action="<?php print nms_h(nms_workspace_url($workspace_section,$workspace_id)); ?>"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="workspace_action" value="cancel_scan"><input type="hidden" name="run_id" value="<?php print (int)$scan['id']; ?>"><button type="submit">Cancel run</button></form><?php } ?></td></tr><?php } if(!$workspace_scan_history['rows']) { ?><tr><td colspan="5">No workspace scan runs yet. Older supplemental results are retained separately.</td></tr><?php } ?></tbody></table></div>
<p>Page <?php print (int)$workspace_scan_history['page']; ?> of <?php print (int)$workspace_scan_history['pages']; ?><?php foreach(['Previous'=>-1,'Next'=>1] as $label=>$delta) { $next=$workspace_scan_history['page']+$delta;if($next<1 || $next>$workspace_scan_history['pages'])continue; ?> · <a href="<?php print nms_h(nms_workspace_url($workspace_section,$workspace_id,['scan_page'=>$next])); ?>"><?php print $label; ?></a><?php } ?></p>
<?php if($workspace_scan) { ?><section id="scan-result"><h3>Scan #<?php print (int)$workspace_scan['id']; ?> results</h3><p><?php print nms_h($workspace_scan['status'].' · '.$workspace_scan['error']); ?></p>
<?php if($workspace_scan['kind']==='native') { ?><p>Results show retained native discovered rows from this run. Cacti may remove a discovered row after automatic addition; scan totals remain in the summary.</p><?php } ?>
<details><summary>Scan summary</summary><pre><?php print nms_h(json_encode(json_decode($workspace_scan['summary_json'],true),JSON_PRETTY_PRINT|JSON_INVALID_UTF8_SUBSTITUTE)); ?></pre></details>
<div class="nms-table-wrap nms-workspace-fit-table"><table class="nms-table" data-server-pagination="true"><thead><tr><th>Address</th><th>Method / port</th><th>Response</th><th>Evidence</th><th>Checked</th></tr></thead><tbody><?php foreach($workspace_scan_results as $result) { ?><tr><td><?php print nms_h($result['address']); ?></td><td><?php print nms_h($result['method'].' / '.($result['port'] ?? '—')); ?></td><td><?php print $result['reachable']?'Received':'No response / error'; ?></td><td><?php print nms_h($result['detail']); ?></td><td><?php print nms_h($result['checked_at']); ?></td></tr><?php } if(!$workspace_scan_results) { ?><tr><td colspan="5">No retained probe results yet.</td></tr><?php } ?></tbody></table></div>
<p>Results page <?php print (int)$workspace_result_page; ?> of <?php print (int)$workspace_result_pages; ?><?php foreach(['Previous'=>-1,'Next'=>1] as $label=>$delta) {$next=$workspace_result_page+$delta;if($next<1 || $next>$workspace_result_pages)continue; ?> · <a href="<?php print nms_h(nms_workspace_url($workspace_section,$workspace_id,['run_id'=>$workspace_scan['id'],'result_page'=>$next])); ?>#scan-result"><?php print $label; ?></a><?php } ?></p></section><?php } ?></section><?php } ?>
