<main class="nms-shell nms-devices-shell nms-configuration-shell">
<div class="nms-heading"><div><p class="nms-eyebrow"><?php print $view==='profiles'?'NMS / Presets':'NMS / Device management'; ?></p><h1><?php print $view==='profiles'?'Equipment profiles':'Configuration'; ?></h1><p><?php print $view==='profiles'?'Define reusable equipment settings from the manufacturer’s manual.':'Read and change documented equipment settings from the assigned collector.'; ?></p></div></div>
<?php if($view!=='profiles'){ $device_nav_active='configuration';$device_nav_id=$host_id;require __DIR__.'/tabs.php'; } ?>
<?php if($error){ ?><div class="nms-form-message error" role="alert"><?php print nms_h($error); ?></div><?php } ?>
<?php if(isset($_GET['saved'])){ ?><div class="nms-form-message success" role="status">Configuration saved.</div><?php } ?>
<?php if(isset($_GET['graphs_created'])){ ?><div class="nms-form-message success" role="status">Numeric graphs are ready in Cacti. Values appear after collection and the next poll.</div><?php } ?>
<?php if(isset($_GET['queued'])){ ?><div class="nms-form-message success" role="status">Request queued for the assigned collector. Refresh to view its result.</div><?php } ?>
<?php if($view==='profiles'){ ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Equipment profiles</h2><a class="nms-node-button" href="devices.php?tab=configuration&amp;view=profiles&amp;new=1">Create profile</a></div><div class="nms-node-table"><table><thead><tr><th>Name</th><th>Manufacturer / model</th><th>Protocol</th><th>Revision</th></tr></thead><tbody><?php foreach($profiles as $profile){ ?><tr><td><a href="devices.php?tab=configuration&amp;view=profiles&amp;profile_id=<?php print (int)$profile['id']; ?>"><?php print nms_h($profile['name']); ?></a></td><td><?php print nms_h($profile['manufacturer'].' / '.$profile['model']); ?></td><td><?php print nms_h($profile['protocol']); ?></td><td><?php print (int)$profile['revision']; ?></td></tr><?php } ?></tbody></table></div></section>
<?php if(isset($_GET['new']) || $profile_id || $_SERVER['REQUEST_METHOD']==='POST'){ ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Profile definition</h2></div><form method="post" class="nms-node-form nms-equipment-profile-form">
<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="action" value="save_profile"><input type="hidden" name="id" value="<?php print (int)$values['id']; ?>"><input type="hidden" name="revision" value="<?php print (int)$values['revision']; ?>">
<div class="nms-node-fields"><?php foreach(['name'=>'Name','manufacturer'=>'Manufacturer','model'=>'Model','manual_reference'=>'Manual reference'] as $key=>$label){ ?><label><?php print $label; ?><input name="<?php print $key; ?>" required value="<?php print nms_h($values[$key]); ?>"></label><?php } ?>
<label>Protocol<select name="protocol"><option value="modbus_rtu" <?php print $values['protocol']==='modbus_rtu'?'selected':''; ?>>Modbus RTU</option><option value="snmp" <?php print $values['protocol']==='snmp'?'selected':''; ?>>SNMP</option></select></label></div>
<label class="nms-equipment-fields">Field definitions (JSON)<textarea name="fields_json" rows="14" required spellcheck="false"><?php print nms_h($values['fields_json']); ?></textarea></label>
<p>Enter a list of fields from the device manual. Each needs key, label, type, writable (true/false), and numeric min/max or string max_length. Modbus fields need a zero-based offset and read function 3 or 4; SNMP fields need a complete numeric oid. Optional unit labels readings. Supported types: Modbus uint16/int16; SNMP integer/unsigned/string.</p>
<p>Assigned profiles cannot be edited. Create a new profile and explicitly reassign devices to change their equipment definitions.</p>
<div class="nms-config-actions"><button class="nms-node-button" type="submit">Save profile</button><a class="nms-cancel-button" href="devices.php?tab=configuration&amp;view=profiles">Cancel</a></div></form></section>
<?php } } else { ?>
<?php if(!$host){ ?><section class="nms-panel"><form method="get" class="nms-node-form"><input type="hidden" name="tab" value="configuration"><?php if($node_id){ ?><input type="hidden" name="node_id" value="<?php print $node_id; ?>"><?php } ?><label>Device<select name="id" onchange="this.form.requestSubmit()"><option value="">Select a device</option><?php foreach($devices as $device){ ?><option value="<?php print (int)$device['id']; ?>" <?php print (int)$device['id']===$host_id?'selected':''; ?>><?php print nms_h($device['description']); ?></option><?php } ?></select></label></form></section><?php } ?>
<?php if($host){ ?>
<section class="nms-panel"><div class="nms-panel-head"><h2><?php print nms_h($host['description']); ?></h2><a class="nms-cancel-button" href="devices.php?tab=connection&amp;id=<?php print $host_id; ?>">Connection</a></div><form method="post" class="nms-node-form">
<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="action" value="assign_equipment"><input type="hidden" name="revision" value="<?php print (int)($assignment['revision'] ?? 0); ?>">
<div class="nms-node-fields"><label>Equipment profile<select name="profile_id"><option value="0">Not assigned</option><?php foreach($profiles as $profile){ ?><option value="<?php print (int)$profile['id']; ?>" <?php print (int)($assignment['profile_id'] ?? 0)===(int)$profile['id']?'selected':''; ?>><?php print nms_h($profile['name'].' · '.$profile['manufacturer'].' / '.$profile['model']); ?></option><?php } ?></select></label>
<label>Collection interval (seconds)<input type="number" name="interval_seconds" min="60" max="86400" value="<?php print (int)($assignment['interval_seconds'] ?? 300); ?>" required></label>
<?php if (!nms_serial_assignment($host_id)) { ?><label>SNMP write credential reference (optional)<input name="credential_ref" maxlength="100" value="<?php print nms_h($assignment['credential_ref'] ?? ''); ?>"></label><?php } ?></div>
<?php if (!nms_serial_assignment($host_id)) { ?><p>Use a credential reference provisioned by the collector administrator. Do not enter a password here.</p><?php } ?><div class="nms-config-actions"><button class="nms-node-button" type="submit">Save equipment setup</button><a class="nms-cancel-button" href="devices.php?tab=edit&amp;id=<?php print $host_id; ?>">Back to device</a></div></form></section>
<?php if($preview){ ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Review change</h2></div><form method="post" class="nms-node-form"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="action" value="apply_write"><input type="hidden" name="review_token" value="<?php print nms_h($preview['token']); ?>">
<p><?php print nms_h($host['description'].' · '.$preview['field']['label']); ?></p><p>Current: <strong><?php print nms_h($preview['before']); ?></strong> → Requested: <strong><?php print nms_h($preview['requested']); ?></strong></p><p>The collector will check the current value again before writing, then read back to verify.</p><button class="nms-node-button" type="submit">Apply change</button> <a class="nms-cancel-button" href="devices.php?tab=configuration&amp;id=<?php print $host_id; ?>">Cancel</a></form></section>
<?php } ?>
<?php if($target){ ?><section class="nms-panel"><div class="nms-panel-head"><h2>Readings</h2><div class="nms-equipment-reading-actions"><form method="post"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><button class="nms-cancel-button" name="action" value="create_graphs" title="Create Cacti graphs to track numeric readings over time. Optional for viewing current values.">Create graphs</button></form><a class="nms-cancel-button" href="devices.php?tab=configuration&amp;id=<?php print $host_id; ?>">Refresh</a></div></div><div class="nms-node-table"><table><thead><tr><th>Setting</th><th>Current value</th><th>Actions</th></tr></thead><tbody>
<?php foreach($target['fields'] as $key=>$field){ $read=$reading_jobs[$key] ?? null; $sample=nms_config_reading($host_id,$key); $result=$read?json_decode($read['result_json'],true):[]; ?><tr><td><?php print nms_h($field['label']); ?></td><td><?php print $sample['status']==='current'?nms_h($sample['value'].' '.$field['unit']):nms_h(ucfirst($sample['status'])); if($sample['observed_at']) print '<br><small>'.nms_h($sample['observed_at']).'</small>'; ?></td><td><form method="post" class="nms-equipment-value-actions"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="field_key" value="<?php print nms_h($key); ?>"><button class="nms-cancel-button" type="submit" name="action" value="read">Read current</button>
<?php if($field['writable'] && $read){ ?><input type="hidden" name="preview_id" value="<?php print (int)$read['id']; ?>"><label>New value<input name="requested" aria-label="<?php print nms_h('New '.$field['label']); ?>"></label><button class="nms-node-button" type="submit" name="action" value="preview_write">Preview change</button><?php } ?></form></td></tr><?php } ?></tbody></table></div></section><?php } ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Change history</h2></div><div class="nms-node-table"><table><thead><tr><th>Request</th><th>Field</th><th>Status</th><th>Before / requested / observed</th><th>Operator</th><th>Time</th></tr></thead><tbody><?php foreach($history as $job){ $result=json_decode($job['result_json'],true) ?: []; $labels=['complete'=>'Read complete','consumed'=>'Read used for change','verified'=>'Verified','unverified'=>'Unverified','failed'=>'Failed','queued'=>'Queued','running'=>'Running']; ?><tr><td>#<?php print (int)$job['id'].' '.nms_h($job['operation']); ?></td><td><?php print nms_h($job['field_key']); ?></td><td><?php print nms_h($labels[$job['status']] ?? $job['status']); ?><?php if(isset($result['error'])){ ?><p><?php print nms_h($result['error']); ?></p><?php } ?></td><td><?php print nms_h($job['before_json'].' / '.$job['requested_json'].' / '.json_encode($result['observed'] ?? $result['value'] ?? null)); ?></td><td><?php print (int)$job['user_id']; ?></td><td><?php print nms_h($job['finished_at'] ?: $job['requested_at']); ?></td></tr><?php } ?></tbody></table></div></section>
<?php } } ?></main>
