<?php /** Node setup and details reuse native host links and permissions. */ ?>
<main class="nms-shell nms-devices-shell">
<div class="nms-heading"><div><p class="nms-eyebrow">NMS / Device management</p><h1>Nodes</h1><p>Organise devices into nodes at their Cacti site.</p></div></div>
<nav class="nms-page-tabs"><a href="devices.php?tab=inventory">Device dashboard</a><a href="devices.php?tab=add">Add device</a><a class="selected" href="devices.php?tab=nodes">Nodes</a></nav>
<?php if ($error) { ?><div class="nms-form-message error" role="alert"><?php print nms_h($error); ?></div><?php } ?>
<?php if (isset($_GET['saved'])) { ?><div class="nms-form-message success" role="status">Node configuration saved.</div><?php } ?>
<?php if (isset($_GET['removed'])) { ?><div class="nms-form-message success" role="status">Node removed. Devices and their monitoring data are preserved.</div><?php } ?>
<?php if ($removing && $selected) { ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Remove <?php print nms_h($selected['name']); ?></h2></div>
<form method="post" class="nms-node-form">
<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="nms_action" value="remove_node"><input type="hidden" name="node_id" value="<?php print $node_id; ?>">
<p>Remove this node container only. Cacti devices, graphs, alarms and connection settings are preserved.</p>
<div class="nms-node-fields"><label>Member devices<select name="member_action" required><option value="">Choose an action</option><option value="unassign">Leave devices unassigned</option><option value="move">Move devices to another node</option></select></label>
<label>Destination for move<select name="target_node_id"><option value="0">Select a node</option><?php foreach($nodes as $target) { if((int)$target['id']===$node_id || (int)$target['site_id']!==(int)$selected['site_id']) continue; ?><option value="<?php print (int)$target['id']; ?>"><?php print nms_h($target['name']); ?></option><?php } ?></select></label>
<label>Enter node code: <?php print nms_h($selected['code']); ?><input name="confirm_code" required autocomplete="off"></label></div>
<button class="nms-node-button" type="submit">Remove node</button> <a class="nms-cancel-button" href="devices.php?tab=nodes&amp;node_id=<?php print $node_id; ?>">Cancel</a></form></section>
<?php } elseif ($editing) { ?>
<section class="nms-panel"><div class="nms-panel-head"><h2><?php print $selected ? 'Edit node' : 'Create node'; ?></h2></div>
<form method="post" class="nms-node-form" data-node-editor>
<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="nms_action" value="save_node"><input type="hidden" name="node_id" value="<?php print (int)$values['node_id']; ?>">
<div class="nms-node-fields">
<label>Name<input name="name" required maxlength="150" value="<?php print nms_h($values['name']); ?>"></label>
<label>Code<input name="code" required maxlength="64" value="<?php print nms_h($values['code']); ?>"></label>
<label>Site<select name="site_id" required data-node-site><option value="">Select a site</option><?php foreach ($sites as $site) { ?><option value="<?php print (int)$site['id']; ?>" <?php print (string)$values['site_id']===(string)$site['id']?'selected':''; ?>><?php print nms_h($site['name']); ?></option><?php } ?></select></label>
<label>Description<textarea name="description" maxlength="512"><?php print nms_h($values['description']); ?></textarea></label>
</div>
<h3>Devices</h3><p>Choose devices from this site. Devices in another node must be moved explicitly through Device Edit. Unchecking a member unassigns it; it does not delete the device.</p>
<label>Search devices<input type="search" data-node-search placeholder="Name or IP address"></label>
<div class="nms-node-members"><?php foreach ($candidates as $device) { $other=!empty($device['node_id'])&&(int)$device['node_id']!==(int)$values['node_id']; ?><label data-node-member data-site="<?php print (int)$device['site_id']; ?>" data-other="<?php print $other?'1':'0'; ?>"><input type="checkbox" name="members[]" value="<?php print (int)$device['id']; ?>" <?php print in_array((string)$device['id'],array_map('strval',(array)$values['members']),true)?'checked':''; ?> <?php print $other?'disabled':''; ?>><span><?php print nms_h($device['description'].' · '.$device['hostname']); ?><?php if($other){ ?> <small>Assigned to another node</small><?php } ?></span></label><?php } ?></div>
<p data-node-empty hidden>No matching devices at this site.</p>
<button type="submit" class="nms-node-button">Save node</button> <a class="nms-cancel-button" href="devices.php?tab=nodes<?php print $selected ? '&amp;node_id='.$node_id : ''; ?>">Cancel</a>
</form></section>
<?php } elseif ($selected) { ?>
<section class="nms-panel"><div class="nms-panel-head"><div><h2><?php print nms_h($selected['name']); ?></h2><p><?php print nms_h($selected['code'].' · '.$selected['site_name']); ?></p></div><?php if($can_manage){ ?><a class="nms-node-button" href="devices.php?tab=nodes&amp;node_id=<?php print $node_id; ?>&amp;edit=1">Edit node</a><?php } ?></div>
<div class="nms-node-body"><p><a href="topology.php?tab=discovered&amp;node_id=<?php print $node_id; ?>">View node topology</a> · <a href="diagnostics.php?node_id=<?php print $node_id; ?>">Node protocol checks</a> · <a href="topology.php?tab=connections&amp;node_id=<?php print $node_id; ?>">Manual and discovered connections</a><?php if($can_manage){ ?> · <a href="devices.php?tab=nodes&amp;node_id=<?php print $node_id; ?>&amp;remove=1">Remove node</a><?php } ?></p><p><?php print nms_h($selected['description']); ?></p><p>Device availability: <strong><?php print nms_h($health['state']); ?></strong> · <?php print $health['total']; ?> accessible devices</p><div class="nms-node-counts"><?php foreach($health['counts'] as $state=>$count){ ?><span><?php print nms_h($state); ?> <strong><?php print $count; ?></strong></span><?php } ?></div><p>Device settings, profiles and discovered connections are read from Cacti when this page opens. Membership stays manual. Counts and alarms reflect only accessible devices; stale readings are Unknown.</p></div>
<div class="nms-node-table"><table><thead><tr><th>Device</th><th>Address</th><th>Status</th><th>Protocols and setup</th><th>Monitoring</th></tr></thead><tbody><?php foreach($members as $device){ $row_health=nms_node_health([$device],time()-max(60,nms_poller_interval()*2));$state=array_search(1,$row_health['counts'],true); ?><tr><td><a href="devices.php?tab=edit&amp;id=<?php print (int)$device['id']; ?>"><?php print nms_h($device['description']); ?></a><?php if((int)$device['site_id']!==(int)$selected['site_id']){ ?><strong> Site changed: reassign this device</strong><?php } ?></td><td><?php print nms_h($device['hostname']); ?></td><td><?php print nms_h($state); ?></td><td><div>Checks: <?php print nms_h($device['diagnostic_profile'] ?: 'Not assigned'); ?></div><div>Discovery: <?php print nms_h($device['discovery_profile'] ?: 'Not assigned'); ?><?php print $device['discovery_profile'] ? ($device['collection_enabled'] && $device['discovery_enabled'] ? ' · Automatic' : ' · Paused') : ''; ?></div><a href="devices.php?tab=edit&amp;id=<?php print (int)$device['id']; ?>">Configure device</a><?php if($device['diagnostic_profile']){ ?> · <a href="diagnostics.php?node_id=<?php print $node_id; ?>&amp;host_id=<?php print (int)$device['id']; ?>">Protocol checks</a><?php } ?></td><td><a href="devices.php?tab=readings&amp;id=<?php print (int)$device['id']; ?>">Readings</a> · <a href="../../graph_view.php?action=preview&amp;host_id=<?php print (int)$device['id']; ?>">Graphs (<?php print (int)$device['graph_count']; ?>)</a></td></tr><?php } ?></tbody></table></div>
</section>
<section class="nms-panel"><div class="nms-panel-head"><h2>Active alarms (<?php print count($alarms); ?>)</h2></div><div class="nms-node-table"><table><thead><tr><th>Device</th><th>Alarm</th><th>Severity</th><th>Status</th><th>Last seen</th></tr></thead><tbody><?php foreach($alarms as $alarm){ ?><tr><td><?php print nms_h($alarm['description']); ?></td><td><?php print nms_h($alarm['title']); ?></td><td><?php print nms_h($alarm['severity']); ?></td><td><?php print nms_h($alarm['status']); ?></td><td><?php print nms_h($alarm['last_seen']); ?></td></tr><?php } ?></tbody></table><?php if(!$alarms){ ?><p>No active alarms for accessible members.</p><?php } ?></div></section>
<?php } else { ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Configured nodes</h2><?php if($can_manage){ ?><a class="nms-node-button" href="devices.php?tab=nodes&amp;new=1">Create node</a><?php } ?></div><div class="nms-node-table"><table><thead><tr><th>Node</th><th>Code</th><th>Site</th></tr></thead><tbody><?php foreach($nodes as $node){ ?><tr><td><a href="devices.php?tab=nodes&amp;node_id=<?php print (int)$node['id']; ?>"><?php print nms_h($node['name']); ?></a></td><td><?php print nms_h($node['code']); ?></td><td><?php print nms_h($node['site_name']); ?></td></tr><?php } ?></tbody></table><?php if(!$nodes){ ?><p>No nodes configured. Create a node and explicitly select its devices.</p><?php } ?></div></section>
<?php } ?>
</main>
