<main class="nms-shell nms-devices-shell"><div class="nms-heading"><h1><?php print nms_h($node['name']); ?> · Configuration</h1><a class="nms-cancel-button" href="devices.php?tab=nodes&amp;node_id=<?php print $node_id; ?>">Back to node</a></div>
<?php $device_nav_active='configuration';$device_nav_id=0;require __DIR__.'/tabs.php'; ?>
<?php if($error){ ?><div role="alert" class="nms-form-message error"><?php print nms_h($error); ?></div><?php } ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Select devices</h2></div><form method="post" class="nms-node-form"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>">
<p>Read the selected devices first, then preview a change. Compatible fields must have the same meaning, units and type. Each device keeps its own connection and register mapping.</p>
<div class="nms-node-members"><?php foreach($members as $member){ ?><label><input type="checkbox" name="members[]" value="<?php print (int)$member['id']; ?>" <?php print in_array((string)$member['id'],array_map('strval',$draft['members']),true)?'checked':''; ?>><?php print nms_h($member['description']); ?></label><?php } ?></div>
<div class="nms-node-fields"><label>Setting<select name="field_key" required><?php foreach($fields as $key=>$label){ ?><option value="<?php print nms_h($key); ?>" <?php print $draft['field_key']===$key?'selected':''; ?>><?php print nms_h($label); ?></option><?php } ?></select></label><label>Requested value<input name="requested" value="<?php print nms_h($draft['requested']); ?>"></label></div>
<button class="nms-cancel-button" name="action" value="read">Read selected</button> <button class="nms-node-button" name="action" value="preview">Preview change</button></form></section>
<?php if($review){ ?><section class="nms-panel"><div class="nms-panel-head"><h2>Review every device</h2></div><form method="post" class="nms-node-form"><input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>"><input type="hidden" name="review_token" value="<?php print nms_h($review['token']); ?>"><table><thead><tr><th>Device</th><th>Current</th><th>Requested</th></tr></thead><tbody><?php foreach($review['rows'] as $row){ ?><tr><td><?php print nms_h($row['name']); ?></td><td><?php print nms_h($row['before']); ?></td><td><?php print nms_h($row['requested']); ?></td></tr><?php } ?></tbody></table><p>Devices execute independently. A failure on one device does not undo verified changes on another.</p><button class="nms-node-button" name="action" value="apply">Apply reviewed changes</button> <a class="nms-cancel-button" href="devices.php?tab=configuration&amp;view=node&amp;node_id=<?php print $node_id; ?>">Cancel</a></form></section><?php } ?>
<section class="nms-panel"><div class="nms-panel-head"><h2>Latest batch results</h2><a class="nms-cancel-button" href="devices.php?tab=configuration&amp;view=node&amp;node_id=<?php print $node_id; ?>">Refresh</a></div><div class="nms-node-table"><table><thead><tr><th>Device</th><th>Status</th><th>Observed value / error</th></tr></thead><tbody><?php foreach($results as $id=>$result){ ?><tr><td>Device <?php print (int)$id; ?></td><td><?php print nms_h(ucfirst($result['status'])); ?></td><td><?php print nms_h($result['error'] ?? $result['details']['error'] ?? $result['details']['observed'] ?? $result['details']['value'] ?? 'Awaiting collector result'); ?></td></tr><?php } ?></tbody></table></div></section></main>
