<?php
$selected_snmp_version = isset_request_var('snmp_version') ? (int) get_filter_request_var('snmp_version') : $cacti_device_defaults['snmp_version'];
$selected_auth_protocol = isset_request_var('snmp_auth_protocol') ? get_nfilter_request_var('snmp_auth_protocol') : $cacti_device_defaults['snmp_auth_protocol'];
$selected_priv_protocol = isset_request_var('snmp_priv_protocol') ? get_nfilter_request_var('snmp_priv_protocol') : $cacti_device_defaults['snmp_priv_protocol'];
$selected_availability = isset_request_var('availability_method') ? (int) get_filter_request_var('availability_method') : $cacti_device_defaults['availability_method'];
$selected_ping_method = isset_request_var('ping_method') ? (int) get_filter_request_var('ping_method') : $cacti_device_defaults['ping_method'];
?>
<link rel="stylesheet" href="<?php print nms_h($nms_asset_base . 'css/nms-snmp-form.css?v=1.0.0'); ?>">
<section class="nms-panel nms-form-panel">
	<div class="nms-panel-head"><div><h2>Add a Cacti device</h2><p>Uses the same Cacti device API as the core console.</p></div></div>
	<form method="post" action="devices.php?tab=add" class="nms-device-form">
		<input type="hidden" name="__csrf_magic" value="<?php print nms_h($nms_csrf_token); ?>">
		<input type="hidden" name="nms_action" value="add_device">
		<fieldset><legend>Device identity</legend><div class="nms-form-grid">
			<label><span>Device name</span><input required name="description" value="<?php print isset_request_var('description') ? nms_h(get_nfilter_request_var('description')) : ''; ?>" placeholder="Branch router 01"></label>
			<label><span>Hostname or IP</span><input required name="hostname" value="<?php print isset_request_var('hostname') ? nms_h(get_nfilter_request_var('hostname')) : '127.0.0.1'; ?>" placeholder="192.0.2.10"></label>
			<label><span>Cacti host template</span><select required name="host_template_id"><option value="">Select template</option><?php foreach ($host_templates as $template) { ?><option value="<?php print (int) $template['id']; ?>" <?php print isset_request_var('host_template_id') && get_filter_request_var('host_template_id') == $template['id'] ? 'selected' : ''; ?>><?php print nms_h($template['name']); ?></option><?php } ?></select></label>
			<label><span>Site</span><select name="site_id"><option value="0">No site</option><?php foreach ($sites as $site) { ?><option value="<?php print (int) $site['id']; ?>"><?php print nms_h($site['name']); ?></option><?php } ?></select></label>
			<label><span>Data collector</span><select name="poller_id"><?php foreach ($pollers as $poller) { ?><option value="<?php print (int) $poller['id']; ?>"><?php print nms_h($poller['name']); ?></option><?php } ?></select></label>
			<label><span>Location</span><input name="location" placeholder="Building / rack"></label>
		</div></fieldset>

		<fieldset class="nms-snmp-fieldset"><legend>SNMP connection</legend>
			<p class="nms-snmp-mode-note" id="nmsSnmpModeNote" aria-live="polite"></p>
			<div class="nms-form-grid">
			<label><span>SNMP version</span><select id="nmsSnmpVersion" name="snmp_version"><option value="2" <?php print $selected_snmp_version === 2 ? 'selected' : ''; ?>>Version 2c</option><option value="1" <?php print $selected_snmp_version === 1 ? 'selected' : ''; ?>>Version 1</option><option value="3" <?php print $selected_snmp_version === 3 ? 'selected' : ''; ?>>Version 3</option></select></label>
			<label class="nms-conditional-field" data-snmp-versions="1,2"><span>Community (v1/v2c)</span><input id="nmsSnmpCommunity" name="snmp_community" value="<?php print nms_h(isset_request_var('snmp_community') ? get_nfilter_request_var('snmp_community') : $cacti_device_defaults['snmp_community']); ?>" placeholder="Cacti default community"></label>
			<label><span>SNMP port</span><input type="number" min="1" max="65535" name="snmp_port" value="<?php print isset_request_var('snmp_port') ? (int) get_filter_request_var('snmp_port') : $cacti_device_defaults['snmp_port']; ?>"></label>
			<label><span>Timeout (ms)</span><input type="number" min="100" max="10000" name="snmp_timeout" value="<?php print isset_request_var('snmp_timeout') ? (int) get_filter_request_var('snmp_timeout') : $cacti_device_defaults['snmp_timeout']; ?>"></label>
			<label class="nms-conditional-field" data-snmp-versions="3"><span>SNMP v3 username</span><input id="nmsSnmpUsername" name="snmp_username" value="<?php print nms_h(isset_request_var('snmp_username') ? get_nfilter_request_var('snmp_username') : $cacti_device_defaults['snmp_username']); ?>"></label>
			<label class="nms-conditional-field" data-snmp-versions="3"><span>SNMP v3 authentication</span><select id="nmsSnmpAuthProtocol" name="snmp_auth_protocol"><option value="[None]" <?php print $selected_auth_protocol === '[None]' ? 'selected' : ''; ?>>None (no authentication)</option><option value="MD5" <?php print $selected_auth_protocol === 'MD5' ? 'selected' : ''; ?>>MD5</option><option value="SHA" <?php print $selected_auth_protocol === 'SHA' ? 'selected' : ''; ?>>SHA</option><option value="SHA224" <?php print $selected_auth_protocol === 'SHA224' ? 'selected' : ''; ?>>SHA224</option><option value="SHA256" <?php print $selected_auth_protocol === 'SHA256' ? 'selected' : ''; ?>>SHA256</option><option value="SHA392" <?php print $selected_auth_protocol === 'SHA392' ? 'selected' : ''; ?>>SHA392</option><option value="SHA512" <?php print $selected_auth_protocol === 'SHA512' ? 'selected' : ''; ?>>SHA512</option></select></label>
			<label class="nms-conditional-field" data-snmp-versions="3" data-snmp-auth-required="1"><span>Authentication password</span><input id="nmsSnmpPassword" type="password" minlength="8" name="snmp_password" value="<?php print nms_h(isset_request_var('snmp_password') ? get_nfilter_request_var('snmp_password') : $cacti_device_defaults['snmp_password']); ?>" autocomplete="new-password"><small>At least 8 characters</small></label>
			<label class="nms-conditional-field" data-snmp-versions="3" data-snmp-auth-enabled="1"><span>SNMP v3 privacy</span><select id="nmsSnmpPrivProtocol" name="snmp_priv_protocol"><option value="[None]" <?php print $selected_priv_protocol === '[None]' ? 'selected' : ''; ?>>None (no encryption)</option><option value="DES" <?php print $selected_priv_protocol === 'DES' ? 'selected' : ''; ?>>DES</option><option value="AES" <?php print $selected_priv_protocol === 'AES' ? 'selected' : ''; ?>>AES</option><option value="AES128" <?php print $selected_priv_protocol === 'AES128' ? 'selected' : ''; ?>>AES128</option><option value="AES192" <?php print $selected_priv_protocol === 'AES192' ? 'selected' : ''; ?>>AES192</option><option value="AES192C" <?php print $selected_priv_protocol === 'AES192C' ? 'selected' : ''; ?>>AES192C</option><option value="AES256" <?php print $selected_priv_protocol === 'AES256' ? 'selected' : ''; ?>>AES256</option><option value="AES256C" <?php print $selected_priv_protocol === 'AES256C' ? 'selected' : ''; ?>>AES256C</option></select></label>
			<label class="nms-conditional-field" data-snmp-versions="3" data-snmp-privacy-required="1"><span>Privacy passphrase</span><input id="nmsSnmpPrivPassphrase" type="password" minlength="8" name="snmp_priv_passphrase" value="<?php print nms_h(isset_request_var('snmp_priv_passphrase') ? get_nfilter_request_var('snmp_priv_passphrase') : $cacti_device_defaults['snmp_priv_passphrase']); ?>" autocomplete="new-password"><small>At least 8 characters</small></label>
			<label class="nms-conditional-field" data-snmp-versions="3"><span>SNMP context</span><input id="nmsSnmpContext" name="snmp_context"></label>
			<label class="nms-conditional-field" data-snmp-versions="3"><span>SNMP engine ID</span><input id="nmsSnmpEngineId" name="snmp_engine_id"></label>
		</div></fieldset>

		<fieldset><legend>Availability and polling</legend><div class="nms-form-grid">
			<label><span>Availability method</span><select name="availability_method"><option value="2" <?php print $selected_availability === 2 ? 'selected' : ''; ?>>SNMP</option><option value="1" <?php print $selected_availability === 1 ? 'selected' : ''; ?>>SNMP and ping</option><option value="4" <?php print $selected_availability === 4 ? 'selected' : ''; ?>>SNMP or ping</option><option value="3" <?php print $selected_availability === 3 ? 'selected' : ''; ?>>Ping only</option><option value="0" <?php print $selected_availability === 0 ? 'selected' : ''; ?>>None</option></select></label>
			<label><span>Ping method</span><select name="ping_method"><option value="1" <?php print $selected_ping_method === 1 ? 'selected' : ''; ?>>ICMP</option><option value="3" <?php print $selected_ping_method === 3 ? 'selected' : ''; ?>>TCP</option><option value="2" <?php print $selected_ping_method === 2 ? 'selected' : ''; ?>>UDP</option></select></label>
			<label><span>Ping port</span><input type="number" min="0" max="65535" name="ping_port" value="<?php print isset_request_var('ping_port') ? (int) get_filter_request_var('ping_port') : $cacti_device_defaults['ping_port']; ?>"></label>
			<label><span>Ping timeout (ms)</span><input type="number" min="1" name="ping_timeout" value="<?php print isset_request_var('ping_timeout') ? (int) get_filter_request_var('ping_timeout') : $cacti_device_defaults['ping_timeout']; ?>"></label>
			<label><span>Ping retries</span><input type="number" min="0" max="10" name="ping_retries" value="<?php print isset_request_var('ping_retries') ? (int) get_filter_request_var('ping_retries') : $cacti_device_defaults['ping_retries']; ?>"></label>
			<label><span>Maximum OIDs per request</span><input type="number" min="1" max="60" name="max_oids" value="<?php print isset_request_var('max_oids') ? (int) get_filter_request_var('max_oids') : $cacti_device_defaults['max_oids']; ?>"></label>
			<label><span>Device threads</span><input type="number" min="1" max="50" name="device_threads" value="<?php print isset_request_var('device_threads') ? (int) get_filter_request_var('device_threads') : $cacti_device_defaults['device_threads']; ?>"></label>
			<label><span>External ID</span><input name="external_id"></label>
		</div></fieldset>
		<label class="nms-wide-field"><span>Notes</span><textarea name="notes" rows="3"></textarea></label>
		<div class="nms-check-row"><label><input type="checkbox" name="proxy" value="1"><span>Allow shared IP for proxy or SNMPSim communities</span></label><label><input type="checkbox" name="disabled" value="1"><span>Create with monitoring disabled</span></label></div>
		<div class="nms-form-actions"><button type="submit">Create device in Cacti</button><a href="?tab=inventory">Cancel</a></div>
	</form>
</section>
